
// Generated by https://quicktype.io

export interface ICountry {
    name:           string;
    topLevelDomain: string[];
    capital:        string;
    altSpellings:   string[];
    subregion:      string;
    region:         string;
    population:     number | string;
    borders?:        string[];
    nativeName:     string;
    currencies:     string;
    languages:      string;
    flag:           string;
}

export interface Currency {
    code:   string;
    name:   string;
    symbol: string;
}

export interface Language {
    iso639_1:   string;
    iso639_2:   string;
    name:       string;
    nativeName: string;
}


// Generated by https://quicktype.io

export interface ICountryResp {
    name:           string;
    capital?:       string;
    region:         Region;
    population:     number;
    flag:           string;
    label:          string;
}


export enum Region {
    Africa = "Africa",
    Americas = "Americas",
    Antarctic = "Antarctic",
    AntarcticOcean = "Antarctic Ocean",
    Asia = "Asia",
    Europe = "Europe",
    Oceania = "Oceania",
    Polar = "Polar",
}
